GET http://localhost:8080/api/user

###

GET http://localhost:8080/api/user/username?username=MctomSpdo

###

GET http://localhost:8080/api/user/email?email=mctom.spdo@gmail.com

###

POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "MctomSpdo",
  "desc": "My description",
  "gender": "m",
  "profilePicturePath": "MctomSpdo-image.png",
  "email": "mctom.spdo@gmail.com",
  "passwordHashValue": "358af81c50e54be08d4b1102656fc836a6e4446a",
  "isDeleted": 0
}

###

DELETE http://localhost:8080/api/user
Content-Type: text/plain

2